"""add_test123

Revision ID: 192daf143b3b
Revises: 20c24a8ca6c0
Create Date: 2015-12-11 18:33:07.396754

"""

# revision identifiers, used by Alembic.
revision = '192daf143b3b'
down_revision = '20c24a8ca6c0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_v2', sa.Column('test_alembic123', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_v2', 'test_alembic123')
    ### end Alembic commands ###
