"""add_test

Revision ID: 20c24a8ca6c0
Revises: ca88780435a
Create Date: 2015-12-11 18:21:31.198099

"""

# revision identifiers, used by Alembic.
revision = '20c24a8ca6c0'
down_revision = 'ca88780435a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_v2', sa.Column('test_alembic', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_v2', 'test_alembic')
    ### end Alembic commands ###
